const data = [
  {
    id: 1,
    description: 'Design a product card with add to cart and favorite button.',
    fonts: ['Barlow Condensed', 'Lato'],
    colors: [
      '#0C090D',
      '#FFFFF6',
      '#000000',
      '#DCD5CB',
      '#E01A4F',
      '#F24E1E',
      '#FF5754',
      '#FFFFFF',
    ],
  },
  {
    id: 2,
    description: 'Generic music player with the regular playback features.',
    fonts: ['Inter'],
    colors: ['#F8F8F8', '#FFFFFF', '#473737', '#664E4D', '#D3A9AA', '#F5B3B3'],
  },
  {
    id: 3,
    description: 'A simple login screen with a signup link at the bottom.',
    fonts: ['Montserrat', 'Inter'],
    colors: [
      '#A884A3',
      '#ECCA54',
      '#000000',
      '#773C6E',
      '#FCEDFA',
      '#DBCCD9',
      '#FFFFFF',
    ],
  },
  {
    id: 4,
    description:
      'Simple registration screen with a login option at the bottom.',
    fonts: ['Roboto', 'Rosarivo'],
    colors: ['#000000', '#ED2941', '#DEDCEF', '#1F1B21', '#222222', '#F8F5F8'],
  },
  {
    id: 5,
    description: "A simple popup window with an 'x' at the top corner.",
    fonts: ['Darker Grotesque'],
    colors: [
      '#222222',
      '#000000',
      '#FBFAF9',
      '#FFFFFF',
      '#3F3F3F',
      '#3D3B3B',
      '#4455EC',
      '#464545',
      '#60635C',
      '#A3EB97',
      '#C5FE69',
      '#E24949',
      '#E34949',
      '#F5F9ED',
      '#F87B7B',
      '#F8F8D2',
      '#F9F9ED',
      '#FCF7CE',
    ],
  },
  {
    id: 6,
    description:
      'A simple calendar design displaying the current month and date.',
    fonts: ['Roboto'],
    colors: [
      '#F9F6F2',
      '#F4F1F2',
      '#000000',
      '#640404',
      '#B4B1B1',
      '#FCFCFC',
      '#FFF2AB',
    ],
  },
  {
    id: 7,
    description: "A generic credit card's front view.",
    fonts: ['Urbanist', 'Nunito Sans'],
    colors: ['#D78629', '#C71228', '#D1D1D1', '#2A2A2A', '#8B8B8B', '#F5F5F5'],
  },
  {
    id: 8,
    description: 'A vertical dropdown category list.',
    fonts: ['Rubik'],
    colors: [
      '#3A434C',
      '#030B12',
      '#686C70',
      '#E7DEE4',
      '#F8F8F8',
      '#56CC69',
      '#7F2121',
      '#F6B452',
      '#F48B75',
      '#FAFAFA',
    ],
  },
  {
    id: 9,
    description: "A confirmation popup with an 'x' in the top corner.",
    fonts: ['DM Sans'],
    colors: [
      '#292C2F',
      '#EEF6FC',
      '#0078D4',
      '#FFBC09',
      '#0364B8',
      '#076FBE',
      '#1490DF',
      '#28A8EA',
      '#2B9FF8',
      '#525658',
      '#71787D',
      '#98D1FC',
      '#9EA2A4',
      '#F4B100',
      '#FFFFFF',
    ],
  },
  {
    id: 10,
    description:
      'A profile view screen with a profile picture and personal info.',
    fonts: ['Twinkle Star', 'Poppins'],
    colors: ['#3157DF', '#738DEA', '#ABBAF2', '#F8F8F8', '#C9C8CE', '#DDE2F2'],
  },
  {
    id: 11,
    description: 'A code field screen to enter a sign-in PIN.',
    fonts: ['Nunito'],
    colors: ['#9353AB', '#F2F2F2', '#8C7594', '#514F4F', '#FFFFFF', '#B5AAB5'],
  },
  {
    id: 12,
    description:
      'A map view screen with a top search bar and a small modal popup.',
    fonts: ['Lato'],
    colors: ['#FFFBFB', '#FF3C8E', '#535353', '#343434', '#757575', '#FF4F99'],
  },
  {
    id: 13,
    description:
      'A simple calculator screen with an example calculation on screen.',
    fonts: ['Niramit'],
    colors: [
      '#F5F5F5',
      '#6CFA55',
      '#AAAAAA',
      '#4D4D4D',
      '#555555',
      '#797979',
      '#80FF7D',
      '#FFFFFF',
    ],
  },
  {
    id: 14,
    description: 'Category screen with a list of products.',
    fonts: ['Poppins'],
    colors: [
      '#4A576B',
      '#FAFAFA',
      '#292A2C',
      '#798CAA',
      '#C6C6C6',
      '#D9E1FF',
      '#324157',
      '#89F3A0',
      '#DAEF57',
      '#40F2FD',
      '#809CFF',
      '#BCCD55',
      '#24A8E1',
      '#D9F1FF',
      '#E3E55E',
      '#F5F5F5',
      '#F86B6B',
    ],
  },
  {
    id: 15,
    description: 'A category card screen with add to cart and product images.',
    fonts: ['Poppins'],
    colors: [
      '#809CFF',
      '#4A576B',
      '#FAFAFA',
      '#292A2C',
      '#6E8BF1',
      '#70829D',
      '#D9E1FF',
      '#324157',
    ],
  },
  {
    id: 16,
    description: 'Articles view on a mobile website.',
    fonts: ['Raleway'],
    colors: [
      '#2B2C2B',
      '#FFFFFF',
      '#565454',
      '#67184C',
      '#BDBEBD',
      '#353635',
      '#72DEED',
      '#E8F088',
    ],
  },
  {
    id: 17,
    description: 'A simple line graph chart with a legend.',
    fonts: ['Space Grotesk', 'Inter'],
    colors: [
      '#B4CB24',
      '#081534',
      '#4A7B19',
      '#598B06',
      '#9CF146',
      '#B9F77B',
      '#C3C5CB',
    ],
  },
  {
    id: 18,
    description: 'A bar graph chart with sample data.',
    fonts: ['Oxygen'],
    colors: [
      '#676767',
      '#9099F1',
      '#B6EAF6',
      '#B8FA85',
      '#E7E268',
      '#F8F8F9',
      '#FB8189',
    ],
  },
  {
    id: 19,
    description: 'A horizontal scrolling carousel.',
    fonts: ['Gg Sans', 'Raleway'],
    colors: [
      '#333333',
      '#000000',
      '#E9E9E9',
      '#F6F6F6',
      '#747373',
      '#221F1F',
      '#867D96',
      '#00643C',
      '#EAAE95',
      '#F296CD',
      '#DB89F8',
      '#F5B52E',
      '#F9680A',
    ],
  },
  {
    id: 20,
    description: 'A dropdown list with country codes.',
    fonts: ['Averia Serif Libre'],
    colors: ['#E6E1DB', '#413D38', '#D5D1CB', '#6F675E', '#F0EBE5', '#625C54'],
  },
  {
    id: 21,
    description: 'A screen to enter a security PIN.',
    fonts: ['Manrope'],
    colors: ['#E9DCDC', '#972B52', '#FFFFFF', '#BC697C', '#F7D7E3'],
  },
  {
    id: 22,
    description: 'A confirmation screen for a transaction.',
    fonts: ['Inter'],
    colors: [
      '#3478F5',
      '#545F74',
      '#E9DCDC',
      '#3478F5',
      '#BBD3FF',
      '#FFFFFF',
      '#204893',
      '#284883',
      '#EEF4FF',
      '#F5F5F5',
    ],
  },
  {
    id: 23,
    description: 'An alarm clock app interface.',
    fonts: ['Nunito'],
    colors: [
      '#071D68',
      '#7992E9',
      '#FFFFFF',
      '#70727B',
      '#EEF0F6',
      '#F5F6F8',
      '#ADAFB6',
      '#455FBA',
    ],
  },
  {
    id: 24,
    description: 'Weather forecast screen of a city.',
    fonts: ['Rubik'],
    colors: ['#F9F6FF', '#4C3876', '#D6D0E4', '#372857', '#241544'],
  },
  {
    id: 25,
    description: 'An FAQ page with cards.',
    fonts: ['Source Sans Pro'],
    colors: [
      '#FAFFE5',
      '#75D926',
      '#B5D926',
      '#D9A726',
      '#40452E',
      '#292D1B',
      '#616359',
      '#FFFFFF',
      '#F0F9C9',
    ],
  },
  {
    id: 26,
    description: 'Expanded view of an FAQ card.',
    fonts: ['Oswald', 'IBM Plex Sans'],
    colors: [
      '#DAC5C5',
      '#864848',
      '#BE4444',
      '#C44848',
      '#D9D9D9',
      '#E3B5B5',
      '#F3F3F3',
      '#FFFFFF',
    ],
  },
  {
    id: 27,
    description: 'A screen with a success message after an action.',
    fonts: ['Poppins'],
    colors: ['#F5F5F5', '#4F5954', '#35684D', '#EDEDED'],
  },
  {
    id: 28,
    description: 'An error screen with invalid code entered.',
    fonts: ['Maven Pro'],
    colors: [
      '#7B52A3',
      '#FCFBEA',
      '#FC7E7E',
      '#633D89',
      '#893D79',
      '#563777',
      '#883F7D',
      '#FAFAFA',
      '#FFFFFF',
    ],
  },
  {
    id: 29,
    description: 'A camera view screen.',
    fonts: ['Inter'],
    colors: ['#F9F9F9', '#454544', '#07005D', '#EEEDFF', '#C3BFFA'],
  },
  {
    id: 30,
    description: 'A screen with social media contact options.',
    fonts: ['Lato'],
    colors: [
      '#FCFCFC',
      '#323718',
      '#D5BB7F',
      '#464B24',
      '#83813F',
      '#2E1E14',
      '#464544',
      '#696765',
    ],
  },
  {
    id: 31,
    description: 'A feedback form with a rating slider and comment box.',
    fonts: ['Poppins'],
    colors: ['#FFFFFF', '#FDE4A4', '#CDFCA8', '#D9F6EC', '#42433F', '#7F807D'],
  },
  {
    id: 32,
    description:
      'A dropdown list with checkboxes, and a save and cancel button.',
    fonts: ['Roboto Serif', 'DM Sans'],
    colors: ['#3E0E31', '#E8DBE4', '#AC93A5', '#EFE0EB', '#FFFFFF'],
  },
  {
    id: 33,
    description: 'Dating app screen with basic functionalities.',
    fonts: ['Anybody', 'Quicksand'],
    colors: [
      '#FDFDFD',
      '#4C4A4B',
      '#DF5121',
      '#757575',
      '#B51F24',
      '#EB1170',
      '#98217E',
      '#3B4960',
      '#5175B2',
    ],
  },
  {
    id: 34,
    description: 'A homepage for a mobile app.',
    fonts: ['Raleway', 'Quintessential'],
    colors: [
      '#161A1D',
      '#7CC7E4',
      '#E6E6E6',
      '#FFFFFF',
      '#898D8E',
      '#353535',
      '#A4A4A4',
    ],
  },
  {
    id: 35,
    description: 'A landing page design.',
    fonts: ['Visby CF'],
    colors: ['#BCBCBC', '#EA5E6F', '#FFFFFF', '#B4E79C', '#EA5E6F', '#EFBC97'],
  },
  {
    id: 36,
    description: 'E-ticket for a flight with relevant info.',
    fonts: ['Inter'],
    colors: ['#1F1D1D', '#F44D57', '#EDEDED', '#FFFFFF', '#ADADAD'],
  },
  {
    id: 37,
    description: 'An electronic ID card with relevant data and a QR code.',
    fonts: ['Manrope'],
    colors: ['#FAFCF9', '#292C27', '#5B9C35', '#DC143C', '#6C7369', '#EEEEEE'],
  },
  {
    id: 38,
    description: 'A live chat UI with a customer support agent.',
    fonts: ['Poppins'],
    colors: ['#FAF7FB', '#281217', '#891654', '#FBE9ED', '#4109B9'],
  },
  {
    id: 39,
    description: 'An inbox with ongoing and previous chats.',
    fonts: ['Comic Sans MS'],
    colors: ['#281217', '#FFFFFF', '#6E6869', '#DFDFE3', '#7472DC'],
  },
  {
    id: 40,
    description: 'A code field screen with a code valid for 2 (two) minutes.',
    fonts: ['Poppins'],
    colors: [
      '#FCFCFC',
      '#43A1A0',
      '#5C5C5B',
      '#4F4F4A',
      '#777775',
      '#F3F0F0',
      '#B0B0AC',
      '#505050',
      '#989898',
      '#D0D0CF',
    ],
  },
  {
    id: 41,
    description: 'A screen with a modal below with a QR code to scan.',
    fonts: ['Poppins'],
    colors: ['#F6F6F6', '#433C47', '#271E2C', '#CCCCBD', '#6D6A6F'],
  },
  {
    id: 42,
    description: 'A screen having a form to input shipping details.',
    fonts: ['Gg Sans'],
    colors: ['#EFEFEF', '#D6D6D6', '#272729', '#00C688', '#F9F9F9'],
  },
  {
    id: 43,
    description:
      'A screen showing various transactions under different headings.',
    fonts: ['IBM Plex Sans'],
    colors: [
      '#FCFCFC',
      '#393A37',
      '#E8E8E8',
      '#545553',
      '#C3EE76',
      '#E5D5F9',
      '#E5D894',
      '#93968E',
      '#777973',
    ],
  },
  {
    id: 44,
    description: 'A screen asking for user consent for T&Cs.',
    fonts: ['Kumbh Sans'],
    colors: [
      '#FFFFFF',
      '#2D56CE',
      '#C6CDE9',
      '#323336',
      '#646770',
      '#A0ABD2',
      '#454A57',
      '#EAEAEA',
      '#F6F6F6',
    ],
  },
  {
    id: 45,
    description: 'A screen showing a dropdown list.',
    fonts: ['Manrope'],
    colors: [
      '#F9F7F7',
      '#464646',
      '#575757',
      '#212020',
      '#AB1D4F',
      '#E7E5E5',
      '#E8CDDA',
      '#828282',
    ],
  },
  {
    id: 46,
    description:
      'An error screen for no internet connection with an illustration.',
    fonts: ['Noto Sans'],
    colors: ['#F1EEEE', '#FFFFFF', '#302E2D', '#494848'],
  },
  {
    id: 47,
    description: 'A screen for an app invitation by a friend.',
    fonts: ['Nunito'],
    colors: ['#313030', '#C3C1C1', '#20D763', '#A6A4A4'],
  },
  {
    id: 48,
    description:
      'A screen showing a menu and options to order or customize food.',
    fonts: ['Lato'],
    colors: [
      '#FFFFFF',
      '#F2F6F9',
      '#737577',
      '#1B2B37',
      '#E9DA4D',
      '#2B2B2B',
      '#131313',
    ],
  },
  {
    id: 49,
    description: "Design an 'about us' subpage for a service.",
    fonts: ['Open Sans'],
    colors: [
      '#F4F4F9',
      '#326EDD',
      '#9C74FF',
      '#AAAAFE',
      '#262629',
      '#F9F9F9',
      '#262629',
      '#505053',
    ],
  },
  {
    id: 50,
    description: 'A screen showing an order summary.',
    fonts: ['Segoe UI'],
    colors: [
      '#0F1019',
      '#F5F5F5',
      '#202330',
      '#939DB8',
      '#6B7286',
      '#C7C7C9',
      '#B6B6B7',
      '#6872D0',
      '#4E5467',
    ],
  },
  {
    id: 51,
    description: 'A screen with options to filter products.',
    fonts: ['Poppins'],
    colors: ['#FBFBFB', '#444242', '#888888', '#9FFF7E'],
  },
  {
    id: 52,
    description: 'A screen to invite your contacts to an app.',
    fonts: ['Raleway'],
    colors: ['#000B21', '#FFFFFF', '#256AF6', '#B6F2FF', '#3C3C3D', '#F4FDFA'],
  },
  {
    id: 53,
    description: 'A screen with a help table to select the right item.',
    fonts: ['Red Hat Display'],
    colors: [
      '#F6F6F6',
      '#1C1C1C',
      '#ECECEC',
      '#5B5B5B',
      '#E8447F',
      '#596393',
      '#474646',
      '#F98EB5',
      '#E7E7E7',
      '#F7F0F0',
      '#F9F4FF',
      '#6F6D6D',
      '#575757',
      '#7A8DF4',
      '#F4F6FF',
    ],
  },
  {
    id: 54,
    description: 'A screen to warn about 18+ content ahead.',
    fonts: ['Plus Jakarta Sans', 'Red Hat Display'],
    colors: ['#FFF570', '#FFF7F7', '#4C4A42', '#606060', '#3E3838'],
  },
  {
    id: 55,
    description: 'An app screen showing various notifications.',
    fonts: ['Inter'],
    colors: [
      '#FFFFFF',
      '#5566FF',
      '#4E4E4E',
      '#888888',
      '#24252D',
      '#52535A',
      '#F2F3FF',
    ],
  },
  {
    id: 56,
    description: 'A screen showing bank account balance and other options.',
    fonts: ['Poppins'],
    colors: [
      '#F8F8F8',
      '#FF5858',
      '#FFDAA2',
      '#322626',
      '#444341',
      '#E5E5E5',
      '#656565',
      '#B6B6B6',
    ],
  },
  {
    id: 57,
    description: 'A screen showing an interface for a blocked payment card.',
    fonts: ['Roboto'],
    colors: [
      '#2D2B2B',
      '#F0F0F0',
      '#272727',
      '#D9D9D9',
      '#C867D1',
      '#5E2A63',
      '#DA5069',
    ],
  },
  {
    id: 58,
    description: 'A photo gallery screen with images.',
    fonts: ['Nunito'],
    colors: ['#FFFFFF', '#393939', '#2F2F2F', '#F6F6F6', '#636363'],
  },
  {
    id: 59,
    description: 'A screen with survey questions.',
    fonts: ['Rubik'],
    colors: ['#564260', '#CDCCCD', '#9C8FA3', '#FCFCFC'],
  },
  {
    id: 60,
    description: 'A modern product detail screen for a mobile app.',
    fonts: ['Poppins'],
    colors: [
      '#484848',
      '#F9F9F9',
      '#C68383',
      '#AFAFAF',
      '#C0C683',
      '#646363',
      '#5A5A5A',
      '#FFFFFF',
      '#D4D4D4',
    ],
  },
  {
    id: 61,
    description: 'Design a search bar with autofill functionality.',
    fonts: ['Public Sans'],
    colors: ['#262626', '#F0F0F0', '#5A5A5A', '#2D2D2D', '#D8D8D8'],
  },
  {
    id: 62,
    description: 'Design an order delivery screen in a mobile app.',
    fonts: ['Fredoka'],
    colors: ['#F6FBFF', '#363C44', '#FFFFFF', '#1F7DE1', '#555555', '#8E8E8E'],
  },
  {
    id: 63,
    description: 'Design a credit card payment screen.',
    fonts: ['Nunito'],
    colors: ['#FDFDFD', '#616161', '#006FCF', '#8CCAFF', '#545454', '#B8B8B8'],
  },
  {
    id: 64,
    description: 'Design a product card with options.',
    fonts: ['Plus Jakarta Sans'],
    colors: [
      '#FBFBFB',
      '#333331',
      '#555554',
      '#F5F5F5',
      '#A3A3A3',
      '#FFF6D2',
      '#FDCC07',
    ],
  },
  {
    id: 65,
    description: 'Design a reservation popup modal.',
    fonts: ['Inter'],
    colors: ['#58138E', '#01FF85', '#DFDFDF', '#FFFFFF', '#343D38'],
  },
  {
    id: 66,
    description: 'Design a store locations map with details.',
    fonts: ['Poppins'],
    colors: ['#FFFFFF', '#5C6ECE', '#D7DDFC', '#3B4681', '#E7EBFE'],
  },
  {
    id: 67,
    description: 'Design a segmented navigation screen in a mobile app.',
    fonts: ['Segoe UI'],
    colors: ['#FDFDF5', '#3A3939', '#C8C8C8', '#FFFFFF', '#EFF5E3'],
  },
  {
    id: 68,
    description: 'A FM radio interface with functionalities.',
    fonts: ['Urbanist'],
    colors: ['#212221', '#E3E3E3', '#2D2D2C', '#BFBDBD', '#CBFE99'],
  },
  {
    id: 69,
    description: 'A simple compass interface with calibration.',
    fonts: ['Work Sans'],
    colors: ['#FFFFFF', '#FDD079', '#363431', '#4F4E4C', '#C6C6C6'],
  },
  {
    id: 70,
    description: 'A simple color wheel interface with miscellaneous features.',
    fonts: ['Work Sans'],
    colors: ['#FFFFFF', '#282A2F', '#4378FF'],
  },
  {
    id: 71,
    description: 'A stopwatch interface with lap and other functionalities.',
    fonts: ['Raleway'],
    colors: ['#2B2B2B', '#FFFDFD', '#EF0576', '#B3B3B3'],
  },
  {
    id: 72,
    description: 'A world clock app with a map and simple functionalities.',
    fonts: ['Lato'],
    colors: ['#EF2A42', '#3A3036', '#595758', '#FFFFFF'],
  },
  {
    id: 73,
    description:
      'An ongoing call interface with assistive features and options.',
    fonts: ['Poppins'],
    colors: ['#232323', '#51F2F8', '#D7D7D7', '#9C9C9C', '#616565', '#4C4F4F'],
  },
  {
    id: 74,
    description:
      'Design a sound recorder app with basic features and a list of recordings.',
    fonts: ['Red Hat Display'],
    colors: ['#FFFFFF', '#3F2C75', '#F7F8FF', '#70619B', '#8F70E9'],
  },
  {
    id: 75,
    description: 'An equalizer app screen with save and other options.',
    fonts: ['Red Hat Display'],
    colors: [
      '#383838',
      '#FFFFFF',
      '#595959',
      '#DDDDDD',
      '#EBFFEC',
      '#E0ECFF',
      '#EAE0FF',
      '#FAF2C8',
    ],
  },
  {
    id: 76,
    description: 'A high-level view of a file manager app.',
    fonts: ['Nunito'],
    colors: ['#312E34', '#FFFFFF', '#565457'],
  },
  {
    id: 77,
    description: 'A QR code scanning app with various options.',
    fonts: ['Poppins'],
    colors: ['#100118', '#E2E1E3', '#7244A6', '#A7A5AA', '#161829', '#BABABA'],
  },
  {
    id: 78,
    description:
      'Design a mobile notification drawer with modes and a clear button.',
    fonts: ['Quicksand'],
    colors: ['#E2E2E2', '#C6C6C6', '#A83B3B', '#5A0F0F', '#340909'],
  },
  {
    id: 79,
    description: 'An app integrations screen with a search feature.',
    fonts: ['Ubuntu'],
    colors: ['#000000', '#FFFFFF', '#282828'],
  },
  {
    id: 80,
    description:
      'An online video streaming player with standard functionalities.',
    fonts: ['Manrope'],
    colors: ['#1E1D22', '#F1EFF9', '#FFFFFF', '#C76565'],
  },
  {
    id: 81,
    description: 'A stock trading chart view with various features.',
    fonts: ['Noto Sans'],
    colors: ['#FFFFFF', '#BBD0FF', '#262B35', '#57637D', '#F77A69'],
  },
  {
    id: 82,
    description:
      'A spatial mixed reality screen with ongoing media and playback options.',
    fonts: ['Inter'],
    colors: ['#D9D9D9', '#ACACAC', '#3A3A39'],
  },
  {
    id: 83,
    description: 'A smart fridge interface with an ordering facility.',
    fonts: ['Plus Jakarta Sans'],
    colors: ['#262020', '#ADFF98', '#F9F6FF', '#969696'],
  },
  {
    id: 84,
    description: 'A smartwatch running app interface with stats.',
    fonts: ['Montserrat'],
    colors: ['#F2F7FF', '#26252A', '#626263', '#D9D6E8'],
  },
  {
    id: 85,
    description:
      'A sleep tracking interface with analytics for a smartwatch app.',
    fonts: ['Inter'],
    colors: [
      '#FFFFFF',
      '#CECECE',
      '#1B1B1B',
      '#6D904F',
      '#E5AE37',
      '#008FD5',
      '#FC4F30',
    ],
  },
  {
    id: 86,
    description: "A VR interface showing the product in a user's room.",
    fonts: ['Poppins'],
    colors: ['#303030', '#FDFDFD', '#040404'],
  },
  {
    id: 87,
    description: 'A smart TV interface for a movie streaming app.',
    fonts: ['Inter'],
    colors: ['#040000', '#FFFFFF'],
  },
  {
    id: 88,
    description: 'A smart TV interface for an OTT app.',
    fonts: ['Lato'],
    colors: ['#1E0524', '#311233', '#E8B9FF', '#C7C7C7'],
  },
  {
    id: 89,
    description:
      'A car dashboard screen with ongoing destination navigation and car information.',
    fonts: ['Nunito'],
    colors: ['#222222', '#33322F', '#C6C6C6', '#FDF9EF', '#B8BFFF'],
  },
  {
    id: 90,
    description:
      'A congratulatory completion certificate for the daily challenges.',
    fonts: ['Plus Jakarta Sans'],
    colors: [
      '#FFFFF0',
      '#FFFFFF',
      '#15BA8A',
      '#3498DB',
      '#DC1D79',
      '#EE5253',
      '#F9C03A',
      '#FDC085',
    ],
  },
];

export default data;
